import {
  PythonIcon,
  JavaIcon,
  TypescriptIcon,
  ReactIcon,
  NextjsIcon,
  TailwindCssIcon,
  JavascriptIcon,
  D3jsIcon,
  PytorchIcon,
  TensorflowIcon,
  SchikitLearnIcon,
  LangchainIcon,
  PandasIcon,
  NumpyIcon,
  NodejsIcon,
  SpringBootIcon,
  DjangoIcon,
  AwsIcon,
  DockerIcon,
  PostgresqlIcon,
  MongodbIcon,
  CppIcon,
  GcpIcon,
  FirebaseIcon,
  KubernetesIcon,
  GraphqlIcon,
  ReduxApiIcon,
  GithubActionsIcon,
  HtmlIcon,
  CssIcon,
  MysqlIcon,
  FastAPIIcon,
  LlmsIcon,
  HuggingFaceIcon,
  SupabaseIcon,
  ThreejsIcon,
  VercelIcon,
  ViteIcon,
} from "@/components/icons";
import type { Skill } from "@/constants";

import {
  SiPython,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiJavascript,
  SiThreedotjs,
  SiPytorch,
  SiTensorflow,
  SiScikitlearn,
  SiLangchain,
  SiPandas,
  SiNumpy,
  SiNodedotjs,
  SiSpringboot,
  SiDjango,
  SiAmazonwebservices,
  SiDocker,
  SiPostgresql,
  SiMongodb,
} from "react-icons/si";

import { Coffee } from "lucide-react";

export const skillRows: Skill[][] = [
  [
    { icon: <PythonIcon className="w-6 h-6" />, name: "Python" },
    { icon: <JavaIcon className="w-6 h-6" />, name: "Java" },
    { icon: <TypescriptIcon className="w-6 h-6" />, name: "TypeScript" },
    { icon: <ReactIcon className="w-6 h-6" />, name: "React" },
    { icon: <NextjsIcon className="w-6 h-6" />, name: "Next.js" },
    { icon: <TailwindCssIcon className="w-6 h-6" />, name: "TailwindCSS" },
    { icon: <JavascriptIcon className="w-6 h-6" />, name: "JavaScript" },
    { icon: <VercelIcon className="w-6 h-6" />, name: "Vercel" },
    { icon: <ThreejsIcon className="w-6 h-6" />, name: "Three.js" },
    { icon: <HtmlIcon className="w-6 h-6" />, name: "HTML" },
    { icon: <CssIcon className="w-6 h-6" />, name: "CSS" },
  ],
  [
    { icon: <PytorchIcon className="w-6 h-6" />, name: "PyTorch" },
    { icon: <TensorflowIcon className="w-6 h-6" />, name: "TensorFlow" },
    { icon: <SchikitLearnIcon className="w-6 h-6" />, name: "Scikit-learn" },
    { icon: <LangchainIcon className="w-6 h-6" />, name: "LangChain" },
    { icon: <PandasIcon className="w-6 h-6" />, name: "Pandas" },
    { icon: <NumpyIcon className="w-6 h-6" />, name: "NumPy" },
    { icon: <CppIcon className="w-6 h-6" />, name: "C++" },
    { icon: <LlmsIcon className="w-6 h-6" />, name: "Gemini LLM" },
    { icon: <GcpIcon className="w-6 h-6" />, name: "GCP" },
  ],
  [
    { icon: <NodejsIcon className="w-6 h-6" />, name: "Node.js" },
    { icon: <SpringBootIcon className="w-6 h-6" />, name: "Spring Boot" },
    { icon: <DjangoIcon className="w-6 h-6" />, name: "Django" },
    { icon: <FastAPIIcon className="w-6 h-6" />, name: "FastAPI" },
    { icon: <AwsIcon className="w-6 h-6" />, name: "AWS" },
    { icon: <DockerIcon className="w-6 h-6" />, name: "Docker" },
    { icon: <PostgresqlIcon className="w-6 h-6" />, name: "PostgreSQL" },
    { icon: <MongodbIcon className="w-6 h-6" />, name: "MongoDB" },
    { icon: <MysqlIcon className="w-6 h-6" />, name: "MySQL" },
    { icon: <GraphqlIcon className="w-6 h-6" />, name: "GraphQL" },
    { icon: <FirebaseIcon className="w-6 h-6" />, name: "Firebase" },
    { icon: <SupabaseIcon className="w-6 h-6" />, name: "Supabase" },
    { icon: <D3jsIcon className="w-6 h-6" />, name: "D3.js" },
    { icon: <HuggingFaceIcon className="w-6 h-6" />, name: "Hugging Face" },
    { icon: <GithubActionsIcon className="w-6 h-6" />, name: "GitHub Actions" },
    { icon: <ViteIcon className="w-6 h-6" />, name: "Vite" },
    { icon: <KubernetesIcon className="w-6 h-6" />, name: "Kubernetes" },
    { icon: <ReduxApiIcon className="w-6 h-6" />, name: "Redux" },
  ],
];

export const capabilityRows: Skill[][] = [
  [
    { icon: <SiPython className="w-6 h-6" />, name: "Python" },
    { icon: <Coffee className="w-6 h-6" />, name: "Java" },
    { icon: <SiTypescript className="w-6 h-6" />, name: "TypeScript" },
    { icon: <SiReact className="w-6 h-6" />, name: "React" },
    { icon: <SiNextdotjs className="w-6 h-6" />, name: "Next.js" },
    { icon: <SiTailwindcss className="w-6 h-6" />, name: "TailwindCSS" },
    { icon: <SiJavascript className="w-6 h-6" />, name: "JavaScript" },
    { icon: <SiThreedotjs className="w-6 h-6" />, name: "Three.js" },
  ],
  [
    { icon: <SiPytorch className="w-6 h-6" />, name: "PyTorch" },
    { icon: <SiTensorflow className="w-6 h-6" />, name: "TensorFlow" },
    { icon: <SiScikitlearn className="w-6 h-6" />, name: "Scikit-learn" },
    { icon: <SiLangchain className="w-6 h-6" />, name: "LangChain" },
    { icon: <SiPandas className="w-6 h-6" />, name: "Pandas" },
    { icon: <SiNumpy className="w-6 h-6" />, name: "NumPy" },
  ],
  [
    { icon: <SiNodedotjs className="w-6 h-6" />, name: "Node.js" },
    { icon: <SiSpringboot className="w-6 h-6" />, name: "Spring Boot" },
    { icon: <SiDjango className="w-6 h-6" />, name: "Django" },
    { icon: <SiAmazonwebservices className="w-6 h-6" />, name: "AWS" },
    { icon: <SiDocker className="w-6 h-6" />, name: "Docker" },
    { icon: <SiPostgresql className="w-6 h-6" />, name: "PostgreSQL" },
    { icon: <SiMongodb className="w-6 h-6" />, name: "MongoDB" },
  ],
];
